# NumPy Tutorial

Tutorial Link: https://www.youtube.com/watch?v=r-uOLxNrNk8&t=5583s&ab_channel=freeCodeCamp.org

In [1]:
import numpy as np
import sys
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))
np.set_printoptions(linewidth=360)

In [35]:
!jt -l

Available Themes: 
   chesterish
   grade3
   gruvboxd
   gruvboxl
   monokai
   oceans16
   onedork
   solarizedd
   solarizedl


In [36]:
!jt -t chesterish -tfs 13 -fs 14

In [7]:
np.array([1,2,3,4,5,6,8])

array([1, 2, 3, 4, 5, 6, 8])

In [8]:
a = np.array([3,7,3,8,9,2,5,78,33])

In [9]:
b = np.array([65,34,24,88,34,73,49])

In [10]:
a[0], a[1]

(3, 7)

In [11]:
a[0:3] #same as python list

array([3, 7, 3])

In [12]:
b[::-1]

array([49, 73, 34, 88, 24, 34, 65])

In [13]:
a[0], a[4], a[-1]

(3, 9, 33)

In [14]:
a[[0,4,-1]] # == a[0], a[2], a[-1]

array([ 3,  9, 33])

In [15]:
b[[4,2,-4]]

array([34, 24, 88])

<h3> data types

In [16]:
a.dtype

dtype('int32')

In [17]:
np.array([8,3.21,7,4,2], dtype=np.float) #np.int8, 32, 64

array([8.  , 3.21, 7.  , 4.  , 2.  ])

In [18]:
np.array([40347092, 234234], dtype=np.int64)

array([40347092,   234234], dtype=int64)

<h3>Dimensions and shapes

In [19]:
A = np.array([
    #0,1,2
    [3,2,6],
    [8,19,4],
    [18,29,44]
])

In [21]:
A.shape # 3 rows, 3 columns

(3, 3)

In [22]:
A.ndim

2

In [23]:
A.size

9

In [24]:
B = np.array([
    [
        [21,43,78],
        [90,78,12],
    ],
    [18,91,78],
    [16,92,78]
], dtype=np.object)

In [27]:
B.ndim

1

In [28]:
A[0][0]

3

In [29]:
A[1][0]

8

In [42]:
A[1,0] #== A[1][0] sekect r2, c1

8

In [43]:
A[0:2] # two rows and two dimensions. 0:2 r1 & r2 completely

array([[ 3,  2,  6],
       [ 8, 19,  4]])

In [44]:
A[0:] #all rows

array([[ 3,  2,  6],
       [ 8, 19,  4],
       [18, 29, 44]])

In [45]:
A[0:1] # row1

array([[3, 2, 6]])

In [47]:
A[:, :2] #all rows (:) but only two coloumns = :2. Selecting rows and columns

array([[ 3,  2],
       [ 8, 19],
       [18, 29]])

In [48]:
A[1:, 1:3] # 2nd row to end, col1 to col3 (excluding col#3). Selecting rows and columns

array([[19,  4],
       [29, 44]])

In [49]:
A[1] = np.array([11,12,19]) #update row 2
A

array([[ 3,  2,  6],
       [11, 12, 19],
       [18, 29, 44]])

In [50]:
A[2] = 99 # same as above, update row 3 with 99 (NumPy automatically expands row with [99,99,99])
A

array([[ 3,  2,  6],
       [11, 12, 19],
       [99, 99, 99]])

<h4>Summary statistics

In [51]:
c = np.array([1,2,4,5,6,7,9,10,4,3,2,2])
c.sum()

55

In [52]:
c.mean()

4.583333333333333

In [53]:
c.std()

2.782634642844

In [54]:
c.var()

7.743055555555556

In [55]:
A

array([[ 3,  2,  6],
       [11, 12, 19],
       [99, 99, 99]])

In [56]:
A.sum()

350

In [57]:
A.mean()

38.888888888888886

In [58]:
A.std()

42.77445874570074

In [59]:
A.var()

1829.6543209876545

In [62]:
A.sum(axis=0) #sum of col1, col2, col3 ~ column or vertical sum

array([113, 113, 124])

In [63]:
A.sum(axis=1) # sum of row1, row2, row3 horizontal dimension

array([ 11,  42, 297])

In [64]:
A.std(axis=0)

array([43.49201715, 43.56094071, 41.12041937])

<h2>Broadcasting and vectorized operations

In [68]:
d = np.arange(10) # equals python range(max)
d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [69]:
d + 10 # doesn't effect original array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [70]:
print('original array', d)
d * 3 # [ x*3 for x in l]

original array [0 1 2 3 4 5 6 7 8 9]


array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [71]:
print('original array', d)
d += 100
d

original array [0 1 2 3 4 5 6 7 8 9]


array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

In [72]:
d # modified by broadcasting operation bcoz d = d + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

In [73]:
e = np.array([10, 11, 102, 103, 14, 105, 106, 107, 18, 109])
d+e # 100+10, 101+11, 102+102, 103+103, 104+14, 105+105, 106+106, 107+107, 108+18, 109+109

array([110, 112, 204, 206, 118, 210, 212, 214, 126, 218])

In [74]:
d * e # same as above but * d.r1*e.r1, d.r2*e.r2 etc

array([ 1000,  1111, 10404, 10609,  1456, 11025, 11236, 11449,  1944, 11881])

<h2>Boolean arrays aka masks

In [82]:
f = np.arange(4, 8)
f += 10
f

array([14, 15, 16, 17])

In [84]:
f[[0,3]]

array([10, 13])

In [85]:
f[[True, False, True, True]]

array([10, 12, 13])

In [90]:
f >= 11 # each r,c is >= 2

array([False,  True,  True,  True])

In [96]:
# find all the values < 12. This is where real power of Boolean arrays used
f[f < 12]

array([10, 11])

In [101]:
g = np.arange(100)
g[g > g.mean()] # filter all from g array, give me all elements whose values is > g.mean()

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
       84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [103]:
g[~(g > g.mean())] # filter all from g array, give me all elements whose values is > g.mean(). Or negation

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [106]:
l = [43,3,2,90]
h = np.array(l)
h

array([43,  3,  2, 90])

In [111]:
h[h < h.mean()]

array([3, 2])

In [112]:
g

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [117]:
g[(g % 2 == 0)] # even numbers

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [118]:
g[(g > 30) & (g % 2 == 0)]

array([32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64,
       66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [124]:
I = np.random.randint(100, size=(3,3)) # super useful to generate random arrays
I

array([[53, 67,  4],
       [98,  1, 85],
       [44,  5, 98]])

In [125]:
I[I>40] # filter values > 40

array([53, 67, 98, 85, 44, 98])

<h2>Linear Algebra

In [127]:
J = np.random.randint(100, size=(3,3))
K = np.random.randint(100, size=(3,2))
J, K

(array([[24, 87, 54],
        [71, 77, 23],
        [99, 26,  3]]),
 array([[18,  8],
        [62,  6],
        [67, 74]]))

In [130]:
J.dot(K) # equals J @ K

array([[9444, 4710],
       [7593, 2732],
       [3595, 1170]])

In [131]:
J @ K

array([[9444, 4710],
       [7593, 2732],
       [3595, 1170]])

In [133]:
J.T #transpose

array([[24, 71, 99],
       [87, 77, 26],
       [54, 23,  3]])

In [135]:
J.T @ K

array([[11467,  7944],
       [ 8082,  3082],
       [ 2599,   792]])

<h3>Size of objects

In [137]:
sys.getsizeof(1)

14

In [138]:
sys.getsizeof(10*100)

14

In [139]:
np.dtype(int).itemsize

4

<b> Lists

In [140]:
sys.getsizeof([])

28

In [141]:
np.array([1]).nbytes

4

In [145]:
l = list(range(10000))

In [146]:
nl = np.arange(10000)

In [147]:
%time np.sum(nl**2)

Wall time: 853 µs


-1724114088

In [151]:
%time sum([x**2 for x in l]) # python took ~5ms where numpy < 1ms

Wall time: 4.77 ms


333283335000

<h3>Useful NumPy functions

<h4>random

In [152]:
np.random.random(size=3)

array([0.35802918, 0.5241926 , 0.72117914])

In [154]:
np.random.normal(size=4)

array([-0.98125986,  0.96497157, -0.14781801, -0.10455805])

In [164]:
np.random.rand(2,10)

array([[0.14090608, 0.09114354, 0.2509045 , 0.08963095, 0.05791764, 0.00746999, 0.94552258, 0.8433777 , 0.04032921, 0.7314507 ],
       [0.77127899, 0.37679265, 0.35882148, 0.11740985, 0.37218902, 0.35894872, 0.69101379, 0.22289111, 0.21704491, 0.25069533]])

In [165]:
np.random.randint(100, size=(3,4))

array([[70, 22, 38, 54],
       [43, 94,  2, 52],
       [33, 97, 23, 97]])

<b>arange

In [166]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [170]:
np.arange(40, 70)

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [171]:
np.arange(0, 1, .1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

<b>resape

In [179]:
np.arange(12).reshape(2,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [180]:
np.arange(12).reshape(6, 2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

<b>linspace

In [3]:
np.linspace(0 ,1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [4]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632, 0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421, 0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211, 0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [5]:
np.linspace(0, 1, 20, False)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 , 0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

<h3>zeros, ones & empty

In [6]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [8]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [9]:
np.zeros((3,3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [10]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [11]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [12]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [13]:
np.empty((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

<h4>identity and eye
   

In [14]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
np.eye(8,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
np.eye(8,4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [22]:
np.eye(8, 4, k=-2)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

"Hello world" [100] 